# Generated by Django 2.1.4 on 2019-01-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='points',
            new_name='point',
        ),
    ]
