# Generated by Django 2.1.4 on 2019-01-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20190101_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='target_date',
        ),
    ]
